### ISSUE TITLE
i3-autoname-workspaces: workspace names get reset upon moving to workspace

### ISSUE THREAD

**Issue by ajeetdsouza** [infokiller/i3-workspace-groups#14]
Workspaces get renamed to `<group>:<workspace_number>` every time I change workspaces.

I'm using `i3-autoname-workspaces --window-icons-all-groups`, and I'm switching between workspaces using `i3-workspace-groups workspace-number x`. This problem does not occur when I switch using i3's default `workspace number x`.

**Comment by infokiller** [comment]
Did you install it using pip? if so, what version are you using? 
`pip list | grep i3-workspace-groups` should show you the version.

**Comment by infokiller** [comment]
And can you give an example of the name they have before being renamed?
How are you setting their name?

**Comment by infokiller** [comment]
OK so I think I know what might be wrong.
You need to call `i3-workspace-groups` with the `--window-icons` argument. So try to use i3-workspace-groups --window-icons workspace-number x`

**Comment by ajeetdsouza** [comment]
Thanks, that solved it!
