### ISSUE TITLE
Strange behavior with multiple monitors?

### ISSUE THREAD

**Issue by khughitt** [infokiller/i3-workspace-groups#18]
Greetings!

I am trying out i3-workspace-groups for the first time on a dual monitor setup, and noticed some strange behavior when switching between workspaces located on different monitors.

I currently have i3 setup to show workspaces 1-3 on one of the monitors by default, and workspaces 4-6 on the other one:

```
workspace "1" output HDMI-0
workspace "2" output HDMI-0
workspace "3" output HDMI-0
workspace "4" output DP-1
workspace "5" output DP-1
workspace "6" output DP-1
```

Aside from that, I am using pretty much all of the suggested default configuration options from the i3-workspaces-groups README.

i3 config: [link](https://github.com/khughitt/dotfiles/blob/3fd69e7db4b6e69419110aaa141ab387734c4b6f/i3)

**Issue**

1. The first thing I notice, is that at first, workspace 1 in the default group is listed as "1", however, as soon as I switch to another workspace in the same group, it gets renamed as "1:1'.

2. The bigger issue, however, is that after switching to a workspace on a different monitor, when I attempt to switch back to workspace 1 on the first monitor,  a second "1" is added at first. Pressing "mod + 1" twice more eventually fixes the issue (see steps & outcomes described below..)

The sequence of steps taken to reproduce the issue are listed below.

**Key**:

- "L" = "left monitor" 
- "R" = right monitor.
- "[n]" = focused workspace

The workspaces listed in i3bar for each monitor are shown after the "L" and "R".

**Steps:**

```
L 4
R [1]
<open term>

<mod + 2>

L 4
R 1:1 [2]

<open term>
<mod + 3>

L 4
R 1:1 2 3

<open term>
<mod + 4>

L [4]
R 1:1 2 3

<mod + 1>
L 4
R [1] 1:1 2
 // original terminal opened in "1" not displayed...

<mod + 1>
L 4
R 1:1 [1] 2
 // workspace "1" moves to right of "1:1" in i3bar, but nothing else changes
 // original terminal opened in "1" not displayed...

<mod + 1>
L 4
R [1:1] 2 3

 // after third "mod + 1" press, workspace "1" goes away, "1:1" is selected, and
 // original term appears again..
```

**Unrelated**

This is not related to the above, but I thought I would ask briefly here and file a separate issue if you think it is possible / worthwhile implementing.

One thing I was thinking it would be useful to do would be to have the ability to indicate that some specific workspace is "shared" across all groups..

For example, it might be nice to dedicate workspace "1" to a web browser, which is shared across all groups.. Then workspace 2-N could be used for various group-specific windows.

Is this something that might be possible with the way i3-workspace-groups is currently implemented?

Regardless, I appreciate you taking the time to put this tool together and making it available to the public! It's a really nice contribution. :+1: 

**System info**

- i3 version 4.17.1 (2019-08-30)
- i3-workspace-groups #66a71c7

**Comment by infokiller** [comment]
Thanks for filing this detailed issue and sorry for the trouble!
I'll take a look at the issues you're seeing now. I don't normally work with multiple monitors, so I'll have to connect my laptop to my desktop monitor to work on the multiple monitors issue.

As for the feature of sharing a workspace between groups: nice suggestion, I can see how this can be useful. Opened issue #19 .

**Comment by infokiller** [comment]
I worked on fixing some multi monitor issues in the past two days. I haven't released them as the default pip version just yet, but I would appreciate if you can test it and let me know if you have any issues. You can do this by running: `pip install --pre --force-reinstall i3-workspace-groups`.

**Comment by infokiller** [comment]
I believe this is fixed, so I'm closing the issue, but if you happen to test this again, please let me know if it worked.

**Comment by khughitt** [comment]
@infokiller Thanks for fixing this! Sorry for the slow response - been a bit busy with work lately so I haven't had the chance to test this out. I should have some time soon though, so I'll give it a shot. I appreciate you looking into it!
