### ISSUE TITLE
The rename feature doesn't seems works.

### ISSUE THREAD

**Issue by damani42** [infokiller/i3-workspace-groups#21]
I use fedora 30 and i3-workspace-groups 0.3.4 version. The behavior of the rename is strange. When I try to rename a workspace in the status bar I have still the old name and the new name. When I want change the workspace with Shift+g I have still  the old name.

**Comment by infokiller** [comment]
Can you please try the latest preview version? you can install it using `python3 -m pip install --pre --force-reinstall i3-workspace-groups`.

Also, how do you rename the workspace?

**Comment by damani42** [comment]
I use the rename command without parameter:

    i3-rename-workspace

Then a prompt is display and I can specify the new name.

**Comment by infokiller** [comment]
OK good, using `i3-rename-workspace` is the right thing to do.
Please update to the preview version using the command above and let me know if things work.

**Comment by infokiller** [comment]
Closing, please reopen if you are able to reproduce in a new version
