### ISSUE TITLE
"values of 'package_data' dict" must be a list of strings (got 'default_config.toml')

### ISSUE THREAD

**Issue by wheatdog** [infokiller/i3-workspace-groups#23]
I found this error while running `python setup.py build`. My python version is 3.7.4. And the version of setuptools 41.6.0. According to [manual](https://docs.python.org/3.7/distutils/setupscript.html#installing-package-data), maybe the value should be list.

https://github.com/infokiller/i3-workspace-groups/blob/8ed633306469160c5b8039a60bb02a7f8c1cab36/setup.py#L32

**Comment by wheatdog** [comment]
Related pull requests in setuptools.

https://github.com/pypa/setuptools/pull/1769

**Comment by infokiller** [comment]
Thanks @wheatdog , fixed in latest master
