### ISSUE TITLE
Switching workspaces behaves weirdly on Sway

### ISSUE THREAD

**Issue by mb720** [infokiller/i3-workspace-groups#26]
Hi!

When switching to workspace using

    bindsym $mod+1 $exec_i3_groups workspace-number 1

I'm taken to a workspace named 1:1.

Similarly, when doing `$mod+2` I end up at 2:2.

Is this intentional?

After assigning a workspace to a group using

    bindsym $mod+Shift+g exec --no-startup-id i3-assign-workspace-to-group

I'm pretty sure there's a bug since when I try to switch to workspace 1, I get a workspace 101:1.

Switching to 2 produces workspace 102:2.

Thanks for taking the time to deal with this!

---

I use the configuration from the README, slightly adapted:

    # Workspaces

    # From https://github.com/infokiller/i3-workspace-groups
    set $exec_i3_groups exec --no-startup-id i3-workspace-groups

    # Switch active workspace group
    bindsym $mod+g exec --no-startup-id i3-switch-active-workspace-group

    # Assign workspace to a group
    bindsym $mod+Shift+g exec --no-startup-id i3-assign-workspace-to-group

    # Select workspace to focus on
    bindsym $mod+m exec --no-startup-id i3-focus-on-workspace

    # Move the focused container to another workspace
    bindsym $mod+Shift+m exec --no-startup-id i3-move-to-workspace

    # Rename/renumber workspace. Uses Super+Alt+n
    bindsym Mod1+Mod4+n exec --no-startup-id i3-rename-workspace

    bindsym $mod+1 $exec_i3_groups workspace-number 1
    bindsym $mod+2 $exec_i3_groups workspace-number 2
    bindsym $mod+3 $exec_i3_groups workspace-number 3
    bindsym $mod+4 $exec_i3_groups workspace-number 4
    bindsym $mod+5 $exec_i3_groups workspace-number 5
    bindsym $mod+6 $exec_i3_groups workspace-number 6
    bindsym $mod+7 $exec_i3_groups workspace-number 7
    bindsym $mod+8 $exec_i3_groups workspace-number 8
    bindsym $mod+9 $exec_i3_groups workspace-number 9
    bindsym $mod+0 $exec_i3_groups workspace-number 10

I'm still on Sway version 1.2.

---
For reproducing this while being on i3, I'd start a new virtual terminal (Ctrl-Alt-F2), install sway and xwayland (for rofi) using `sudo pacman -Sy sway xorg-server-xwayland`. Then, after editing Sway's config file at `~/.config/sway/config` I'd start it with `sway`.

**Comment by infokiller** [comment]
Yes, this is intentional- every workspace groups is allocated 100 prefix numbers, so for example the first/active workspace group can have names like `n:n` for `1 <= n < 100`, while for the second group `101 <= n < 200`. But the prefix numbers are actually an implementation detail- if you set `strip_workspace_numbers yes` in your config (like suggested in the README) they should disappear. Can you try adding this to your config?

**Comment by mb720** [comment]
Thanks! After adding the following the workspaces are named as described.

    bar {
        ...
        strip_workspace_numbers yes
        ...
    }
