### ISSUE TITLE
Assing programs to workspaces + create Groups at startup

### ISSUE THREAD

**Issue by rayvermey** [infokiller/i3-workspace-groups#30]
Hi
Nice tool this is!
I have 3 questions:
1) can i create workspaces at startup?
I would like to have some groups created like WORK, HOME, CHAT, WEB etc.
No i create them on the fly which is nice but i have to do that every time
Can i predefine them in my config?

2) Can is assign programs to workspaces when they are started?
Like i would like to assign Chromium to Workspace 1 in Group Web when i start it.
And Spotify to Workspace 3 in group Music.

3) maybe part of 2) : now when i have 3 workspaces in CHAT they are called Chat:1 Chat:2 and Chat:3, i would name them Chat:1 IRC, Chat 2: WHATSAPP for instance.
Is that possible too?

Thanks for your time..

Ray

**Comment by infokiller** [comment]
Hey!

1. There's no direct support for that and it's out of scope for this project, but I guess you could write a script to do that in combination with [i3 layout saving/restoring](https://i3wm.org/docs/layout-saving.html). See also [i3-resurrect](https://github.com/JonnyHaystack/i3-resurrect).

2. This is not supported but it's actually in scope. I'll open a feature request for this.

3. Yes, you can name any workspace in a group using the provided `i3-rename-workspace` (installed when you install it with pip).
