### ISSUE TITLE
Odd workspace naming 

### ISSUE THREAD

**Issue by kalimalrazif** [infokiller/i3-workspace-groups#32]
Hi,

Mi workspace names are 1:1 or 2:2 when I assign a name then they are for example 101:work:1  after messing around with names and groups the workspace names never return to 1:1 or something like that. I commented the name set for workspaces on mi i3 config.

Besides on screenshot you can see there is a utf-8 code on default group name.
![Screenshot from 2020-07-06 19-11-11](https://user-images.githubusercontent.com/2915349/86664725-f8f84b00-bfbc-11ea-9db7-89b48c05a6ff.png)

The n:n nomenclature is normal? Thanks in advance

**Comment by infokiller** [comment]
Hi, you need to make sure you have `strip_workspace_numbers yes` in your config so that the workspace numbers only appear once.
Are you using i3 bar?
Your i3 config should have something like this:

```
bar {
  strip_workspace_numbers yes
  # The rest of your bar config goes below.
  # ...
}
```

**Comment by kalimalrazif** [comment]
Thanks!!!

Works like a charm!
Nom
Atte.
Nomar Mora
