### ISSUE TITLE
Assigning workspace to another group with a taken number

### ISSUE THREAD

**Issue by Syphdias** [infokiller/i3-workspace-groups#33]
I'm searching for a way to directly assign a workspace with the same number to another group. Currently if there is a collision nothing happens and it fails silently. It would be great if it would get the lowest free number if the number is taken.

Steps to reproduce:
1. open a window in the default group in workspace `1`
2. open a new group named `new`
3. make use you are also on workspace `new:1`
4. open a terminal
5. try to assign workspace to default group with either of these commands:
```
❯ i3-assign-workspace-to-group                                          
Workspace with local number "1" already exists in group: "": "100101:​​​​1"
❯ i3-workspace-groups --renumber-workspaces assign-workspace-to-group '' # I hoped renumber-workspaces would help, but it makes not difference
Workspace with local number "1" already exists in group: "": "100101:​​​​1"
```

Workaround:
1. find a number that is not taken in default group
2. assign workspace to default group

**Comment by infokiller** [comment]
I will look into adding an option to do what you want (which will be available both in the config file and as a CLI param).

**Comment by infokiller** [comment]
@Syphdias I added support for the `--use-next-available-number` flag in the latest pre-release version, as well as the `use_next_available_number` option in the config file. Install it using python3 -m pip install --pre --force-reinstall i3-workspace-groups.
