### ISSUE TITLE
Strip workspace numbers in polybar

### ISSUE THREAD

**Issue by stexus** [infokiller/i3-workspace-groups#36]
Is it possible to strip the implementation detail numbers in polybar? I've looked through all the relevant issues and they seem to all refer to i3bar. 

Thanks for your work!

**Comment by infokiller** [comment]
Yes, see the `strip-wsnumbers = true` option: https://github.com/polybar/polybar/wiki/Module:-i3#basic-settings
This is actually not related to i3-workspace-groups, this is a feature of every reasonable i3 bar.

Also see this issue: https://github.com/infokiller/i3-workspace-groups/issues/3

**Comment by stexus** [comment]
Oh wow I completely missed that when looking through the Polybar settings. TIL, thanks!
