### ISSUE TITLE
No icon show

### ISSUE THREAD

**Issue by BenSYZ** [infokiller/i3-workspace-groups#45]
I've read this https://github.com/infokiller/i3-workspace-groups/issues/16#issuecomment-529221718

```sh
i3 version:  4.19.1 (2021-02-01) © 2009 Michael Stapelberg and contributors
	from i3-gaps
i3blocks version: 1.5
i3ipc: 2.2.1
python 3.9.4
```

I've set the icons section enabled, but there is no icon showing in status bar. I wonder if it's because the version of `i3ipc` is too high? If so, would you mind setting the version limit in `environment.yml`? If not could you help me to solve the problem? Thanks a lot!

**Comment by infokiller** [comment]
Hi,
Maybe the issue is that the font you are using for the i3 bar doesn't support the icons? Can you try to set the icons in the config.toml file to regular characters and see if it works?

How did you install it? using pip or conda? can you run `pip list` if you use pip?
The version of i3ipc you posted should be fine.

**Comment by BenSYZ** [comment]
I'm so sorry to say that the problem disappeared. What I've done:
1. Set `default_icon = ''` (firefox)
2. When I change the work groups, the icon appeared, it seems that all the icons are set to be the firefox one, including the chromium(I forget, maybe that just another firefox opened in that workspace)
3. And then I change the default the icon to the chrome, after which everything changed.
4. After changing the work groups, the workspace containing chromium reserved the icon, but not for the others, which only show 4x. At that time I realized that I need to set the `match` in `icons.rules` section, because I use `alacritty` as my default terminal, and `class` of firefox is `firefox` but not `Firefox`.

Before this issue is raised, I've try to set the default icon, but failed. I have forgot the details.

Sorry for taking your time. I had so less confidence when I saw the icon not displayed and i3ipc version issue was mentioned. And sorry for my providing so less information. If I try to find more evidence, maybe this problem will be solved by myself. 

Besides,
* font in i3blocks is set to be SauceCodePro Nerd Font, and it support the icons.
* I'm an arch user, so I install the package with AUR (someone have already write the packaging script)

---
By the way, it might be better to mention `i3-autoname-workspaces` in the readme.

**Comment by infokiller** [comment]
Thanks, I will try to document `i3-autoname-workspaces` more clearly
BTW, it's better not to install the AUR package, since I'm not maintaining it, and it may be out of date.

**Comment by BenSYZ** [comment]
Thanks for your kind reminder. But don't worry, because as long as the [PKGBUILD](https://wiki.archlinux.org/index.php/PKGBUILD) file, a shell script containing the build information, has no errors. I can then use the arch package manager, `pacman` (or exactly [pacman wrapper](https://wiki.archlinux.org/index.php/AUR_helpers)) to update. 

> makepkg can automatically update this variable by defining a pkgver() function in the PKGBUILD. See VCS package guidelines#The pkgver() function for details.
https://wiki.archlinux.org/index.php/PKGBUILD#pkgver

You could also see:
https://wiki.archlinux.org/index.php/VCS_package_guidelines
