### ISSUE TITLE
Multiple monitor support

### ISSUE THREAD

**Issue by kayasoze** [infokiller/i3-workspace-groups#7]
It would be great if switching to a group would activate it on all monitors on which it exists.

**Comment by infokiller** [comment]
Sure thing- didn't get the chance to test it on multiple monitors yet but I'll do it soon.

**Comment by infokiller** [comment]
I just played a bit with multi monitor setup with my laptop and an external monitor.
There's a few issues I noticed, but they are mostly related to the fact that the multi monitor model is not well defined yet.
I see two possible approaches:

1. An active group per monitor. When a user switches the active group, it switches it for the current monitor, but not **necessarily** for the others, which may not even have a workspace from that group.
2. Single active group for all monitors. When a user switched the active group, it switches it in all monitors. If needed, it will create new workspaces for the active groups in monitors that don't have workspaces from that group.

I think that the main advantage of the first one is that it's easier to implement in a way that is not surprising to the user. The second approach may create new empty workspaces, and I think that can be strange for a user.

The first one is also more flexible, but that's less important IMO. It can enable, for example, having one project open on the first monitor and another on the second. Whenever you change focus to one of the monitors, you will be automatically in the active group of that monitor.

Any thoughts?
What behavior would you expect in a multi monitor setup?

**Comment by bacardi55** [comment]
Hi,
I haven't installed your project yet but I am very interested :)
That being said, I'm 99% of the time using 2 or 3 monitor (including the laptop screen) and my personal view is that option 1 makes more sens.

In 2 monitor situation: I have work workspace on the main monitor and often switch between work/personal stuff on the 2nd screen independently (eg for text/chat)
In 3 monitor situation, I always have 2 work related monitor and 1 more personal.

I think people could add more complex keybind in their conf to simulate option 2 based on option 1.

Looking forward to play with workspace groups :)

**Comment by kayasoze** [comment]
I was imagining something akin to 1.  As I originally stated, switching to a group would switch it on all monitors where it exists.  In cases where users do not want this behavior, they would not define a group on more than one monitor.

**Comment by infokiller** [comment]
@kayasoze I ended up making switching the active group on all monitors that have workspaces in this group the default, so you don't need to use another argument.
